#!/bin/bash

positive=0
negative=0
zero=0

echo "Enter 10 numbers:"
for ((i=1; i<=10; i++)); do
    read num
    if [ $num -gt 0 ]; then
        ((positive++))
    elif [ $num -lt 0 ]; then
        ((negative++))
    else
        ((zero++))
    fi
done

echo "Positive numbers: $positive"
echo "Negative numbers: $negative"
echo "Zeroes: $zero"
